---
title: "Data processing for meta analysis"
author: "Ian Hussey & Jamie Cummins"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}

knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)

```

# Participant level data

```{r}

# dependencies
library(tidyverse)

# Trial level data

# get data and do exclusions

exp_1_trial_level <- read.csv("../../experiment 1/data/processed/trial_level_ia_amp_positive_negative_data.csv") %>%
  mutate(experiment = 1) %>%
  filter(complete_data == TRUE & 
           self_exclusion_1 == "Yes, use my data")

exp_2_trial_level <- read.csv("../../experiment 2/data/processed/trial_level_ia_amp_positive_negative_data.csv") %>%
  mutate(experiment = 2) %>%
  filter(complete_data == TRUE & 
           self_exclusion_1 == "Yes, use my data")

exp_3_trial_level <- read.csv("../../experiment 3/data/processed/trial_level_ia_amp_positive_negative_data.csv") %>%
  mutate(experiment = 3) %>%
  filter(complete_data == TRUE & 
           self_exclusion_1 == "Yes, use my data" &
           party == "democrat")

exp_4_trial_level <- read.csv("../../experiment 4/data/processed/trial_level_ia_amp_positive_negative_data.csv") %>%
  mutate(experiment = 4) %>%
  filter(complete_data == TRUE & 
           self_exclusion_1 == "Yes, use my data" &
           party %in% c("democrat", "republican"))

exp_5_trial_level <- read.csv("../../experiment 5/data/processed/trial_level_ia_amp_positive_negative_data.csv") %>%
  mutate(experiment = 5) %>%
  filter(complete_data == TRUE & 
           self_exclusion_1 == "Yes, use my data")

combined_trial_level_data <- bind_rows(exp_1_trial_level, 
                                       exp_2_trial_level,
                                       exp_3_trial_level,
                                       exp_4_trial_level,
                                       exp_5_trial_level) %>%
  mutate(unique_id = paste(experiment, subject, sep = "_"),
         prime_type = dplyr::recode(prime_type,
                                    "prime_type_A" = "Positive",
                                    "prime_type_B" = "Negative"),
         prime_type = fct_relevel(prime_type,
                                  "Negative",
                                  "Positive")) %>%
  dplyr::select(-subject)

# write to disk 
write_csv(combined_trial_level_data, "combined_trial_level_data.csv")

```

```{r}

## participant level
exp_1 <- read.csv("../../experiment 1/data/processed/processed_data.csv") %>%
  mutate(experiment = 1, 
         age = as.character(age),
         awareness = as.numeric(awareness),
         influence_general = as.numeric(influence_general),
         intentionality = as.numeric(intentionality),
         unintentionality = as.numeric(unintentionality)) %>%
  filter(complete_data == TRUE & 
           self_exclusion_1 == "Yes, use my data")

exp_2 <- read.csv("../../experiment 2/data/processed/processed_data.csv") %>%
  mutate(experiment = 2, 
         age = as.character(age),
         awareness = as.numeric(awareness),
         influence_general = as.numeric(influence_general),
         intentionality = as.numeric(intentionality),
         unintentionality = as.numeric(unintentionality)) %>%
  dplyr::select(-IA_AMP_uninfluenced_effect_positive_negative) %>%  # additional unneeded column
  filter(complete_data == TRUE & 
           self_exclusion_1 == "Yes, use my data")

exp_3 <- read.csv("../../experiment 3/data/processed/processed_data.csv") %>%
  mutate(experiment = 3, 
         age = as.character(age),
         awareness = as.numeric(awareness),
         influence_general = as.numeric(influence_general),
         intentionality = as.numeric(intentionality),
         unintentionality = as.numeric(unintentionality)) %>%
  filter(complete_data == TRUE & 
           self_exclusion_1 == "Yes, use my data" &
           party == "democrat")

exp_4 <- read.csv("../../experiment 4/data/processed/processed_data.csv") %>%
  mutate(experiment = 4, 
         age = as.character(age),
         awareness = as.numeric(awareness)) %>%
  filter(complete_data == TRUE & 
           self_exclusion_1 == "Yes, use my data" &
           party %in% c("democrat", "republican"))

exp_5 <- read.csv("../../experiment 5/data/processed/processed_data.csv") %>%
  mutate(experiment = 5,
         age = as.character(age),
         awareness = as.numeric(awareness),
         influence_general = as.numeric(influence_general),
         intentionality = as.numeric(intentionality),
         unintentionality = as.numeric(unintentionality)) %>%
  filter(complete_data == TRUE & 
           self_exclusion_1 == "Yes, use my data")

combined_participant_level_data <- bind_rows(exp_1, exp_2, exp_3, exp_4, exp_5) %>%
  dplyr::select(sort(names(.))) %>%
  
  # two influence rates captured in experiment 4 - make the standard influence rate column
  # reflect the influence rate of the positive-negative IA-AMP
  mutate(influence_rate = ifelse(is.na(influence_rate), 
                                 influence_rate_positive_negative, influence_rate)) %>%
  mutate(unique_id = paste(experiment, subject, sep = "_")) %>%
  mutate(gender = case_when(str_detect(gender, "F") ~ "female",
                            str_detect(gender, "f") ~ "female",
                            str_detect(gender, "Female") ~ "female",
                            str_detect(gender, "W") ~ "female",
                            str_detect(gender, "w") ~ "female",
                            str_detect(gender, "M") ~ "male",
                            str_detect(gender, "m") ~ "male",
                            str_detect(gender, "Male") ~ "male",
                            TRUE ~ "other")) %>%
  mutate(age = as.numeric(age)) %>%
  dplyr::select(unique_id, age, gender, party, politics, experiment,
                AMP_effect_positive_negative, AMP_effect_obama_trump, 
                IA_AMP_effect_positive_negative, 
                influence_rate, influence_general,
                IA_AMP_effect_obama_trump)

```


# compute influenced and uninfluenced effects

```{r}
# experiment 1

# uninfluenced
exp_1_uninfluenced <- exp_1_trial_level %>%
  filter(influenced == 0) %>%
  mutate(unique_id = paste(experiment, subject, sep = "_")) %>%
  group_by(unique_id, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_uninfluenced_effect_positive_negative = round(prime_type_A - prime_type_B, 2)) %>%
  select(unique_id, IA_AMP_uninfluenced_effect_positive_negative) %>%
  semi_join(combined_participant_level_data, by = "unique_id")

# influenced
exp_1_influenced <- exp_1_trial_level %>%
  filter(influenced == 1) %>%
  mutate(unique_id = paste(experiment, subject, sep = "_")) %>%
  group_by(unique_id, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_influenced_effect_positive_negative = round(prime_type_A - prime_type_B, 2)) %>%
  select(unique_id, IA_AMP_influenced_effect_positive_negative) %>%
  semi_join(combined_participant_level_data, by = "unique_id")

# experiment 2

# uninfluenced
exp_2_uninfluenced <- exp_2_trial_level %>%
  filter(influenced == 0) %>%
  mutate(unique_id = paste(experiment, subject, sep = "_")) %>%
  group_by(unique_id, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_uninfluenced_effect_positive_negative = round(prime_type_A - prime_type_B, 2)) %>%
  select(unique_id, IA_AMP_uninfluenced_effect_positive_negative) %>%
  semi_join(combined_participant_level_data, by = "unique_id")

# influenced
exp_2_influenced <- exp_2_trial_level %>%
  filter(influenced == 1) %>%
  mutate(unique_id = paste(experiment, subject, sep = "_")) %>%
  group_by(unique_id, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_influenced_effect_positive_negative = round(prime_type_A - prime_type_B, 2)) %>%
  select(unique_id, IA_AMP_influenced_effect_positive_negative) %>%
  semi_join(combined_participant_level_data, by = "unique_id")

# experiment 3

# uninfluenced
exp_3_uninfluenced <- exp_3_trial_level %>%
  filter(influenced == 0) %>%
  mutate(unique_id = paste(experiment, subject, sep = "_")) %>%
  group_by(unique_id, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_uninfluenced_effect_positive_negative = round(prime_type_A - prime_type_B, 2)) %>%

  select(unique_id, IA_AMP_uninfluenced_effect_positive_negative) %>%
  semi_join(combined_participant_level_data, by = "unique_id")

# influenced
exp_3_influenced <- exp_3_trial_level %>%
  filter(influenced == 1) %>%
  mutate(unique_id = paste(experiment, subject, sep = "_")) %>%
  group_by(unique_id, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_influenced_effect_positive_negative = round(prime_type_A - prime_type_B, 2)) %>%
  select(unique_id, IA_AMP_influenced_effect_positive_negative) %>%
  semi_join(combined_participant_level_data, by = "unique_id")

# experiment 4

# uninfluenced
exp_4_uninfluenced <- exp_4_trial_level %>%
  filter(influenced == 0) %>%
  mutate(unique_id = paste(experiment, subject, sep = "_")) %>%
  group_by(unique_id, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_uninfluenced_effect_positive_negative = round(prime_type_A - prime_type_B, 2)) %>%
  select(unique_id, IA_AMP_uninfluenced_effect_positive_negative) %>%
  semi_join(combined_participant_level_data, by = "unique_id")

# influenced
exp_4_influenced <- exp_4_trial_level %>%
  filter(influenced == 1) %>%
  mutate(unique_id = paste(experiment, subject, sep = "_")) %>%
  group_by(unique_id, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_influenced_effect_positive_negative = round(prime_type_A - prime_type_B, 2)) %>%
  select(unique_id, IA_AMP_influenced_effect_positive_negative) %>%
  semi_join(combined_participant_level_data, by = "unique_id")

# experiment 5

# uninfluenced
exp_5_uninfluenced <- exp_5_trial_level %>%
  filter(influenced == 0) %>%
  mutate(unique_id = paste(experiment, subject, sep = "_")) %>%
  group_by(unique_id, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_uninfluenced_effect_positive_negative = round(prime_type_A - prime_type_B, 2)) %>%
  select(unique_id, IA_AMP_uninfluenced_effect_positive_negative) %>%
  semi_join(combined_participant_level_data, by = "unique_id")

# influenced
exp_5_influenced <- exp_5_trial_level %>%
  filter(influenced == 1) %>%
  mutate(unique_id = paste(experiment, subject, sep = "_")) %>%
  group_by(unique_id, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_influenced_effect_positive_negative = round(prime_type_A - prime_type_B, 2)) %>%
  select(unique_id, IA_AMP_influenced_effect_positive_negative) %>%
  semi_join(combined_participant_level_data, by = "unique_id")

# join the influenced and uninfluenced effects
influenced_effects <- exp_1_influenced %>%
  bind_rows(exp_2_influenced) %>%
  bind_rows(exp_3_influenced) %>%
  bind_rows(exp_4_influenced) %>%
  bind_rows(exp_5_influenced)

uninfluenced_effects <- exp_1_uninfluenced %>%
  bind_rows(exp_2_uninfluenced) %>%
  bind_rows(exp_3_uninfluenced) %>%
  bind_rows(exp_4_uninfluenced) %>%
  bind_rows(exp_5_uninfluenced)

influenced_and_uninfluenced_effects <- uninfluenced_effects %>%
  left_join(influenced_effects, by = "unique_id")


# join into main df
full_combined_participant_level_data <- combined_participant_level_data %>%
  left_join(influenced_and_uninfluenced_effects, by = "unique_id")


# write to disk 
write_csv(full_combined_participant_level_data, "combined_participant_level_data.csv")

```

```
