---
title: "Study 3"
subtitle: "Processing"
author: "Jamie Cummins & Ian Hussey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r include=FALSE}

knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE, 
                      cache = TRUE,
                      echo = FALSE)

```

```{r}

# dependencies
library(tidyverse)

# get data
demographics_df    <- read.csv("raw/demographics_18_08_09.csv")
intentional_AMP_df <- read.csv("raw/modified_intentionality_amp_18_08_09.csv")
standard_AMP_df    <- read.csv("raw/standard_amp_18_08_09.csv")
questions_df       <- read.csv("raw/post-questions_18_08_09.csv")

```

```{r questions and demographics}

# match Prolific IDs to subject numbers (for payment processing)
prolificid_df <- demographics_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  filter(trialcode == "ProlificCode") %>%
  dplyr::select(subject, response) 

# Screen questions df for unique values, thus removing duplicates
self_exclusion <- questions_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  dplyr::select(subject, trialcode, response)

# Join the above two dfs, filter for only the appropriate number of rows
screen <- full_join(prolificid_df, self_exclusion, by="subject") %>%
  group_by(subject) %>% 
  filter(n() == 8) %>%
  dplyr::rename(prolificid = response.x, 
                response = response.y) %>%
  mutate(response = as.character(response))

# Take the questions_df, remove potential duplicates, and then spread
screen_qs <- questions_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  select(subject, trialcode, response) %>%
  group_by(subject) %>%
  spread(trialcode, response) %>%
  ungroup() %>% 
  na.omit

```

```{r AMP data}

# Manipulate intentional AMP df so that "influenced" refers to whether the trial response 
# indicated the absence (0) or presence (1) of an influence of the prime
# Also filters incomplete AMP data, and ensures that only participants 
# who answers all of the post-questions are included
int_AMP_cleaned <- intentional_AMP_df %>%
  mutate(influenced = ifelse(trialcode == "intention_check" & correct == 1, 1, 0)) %>%
  mutate(influenced = lead(influenced)) %>%
  filter(trialcode == "prime_positive" | trialcode == "prime_negative") %>%
  mutate(trialcode = ifelse(trialcode == "prime_positive", 1, 0)) %>%
  group_by(subject) %>% 
  filter(n() == 72) %>%
  semi_join(., screen, by = "subject") %>%
  dplyr::rename(prime_type = trialcode)

# Do basically the same as above (without leading) for the standard AMP
std_AMP_cleaned <- standard_AMP_df %>%
  filter(trialcode == "prime_obama" | trialcode == "prime_trump") %>%
  mutate(trialcode = ifelse(trialcode == "prime_obama", 1, 0)) %>%
  group_by(subject) %>% 
  filter(n() == 72) %>%
  semi_join(., screen, by = "subject") %>%
  semi_join(., int_AMP_cleaned, by = "subject") %>%
  dplyr::rename(prime_type = trialcode)

```

# Subject-level data-frames 


```{r subject-level dfs}

# Creates an amp_effect column giving the AMP effect on the IA-AMP for each subject.
int_joiner <- int_AMP_cleaned %>%
  group_by(subject, prime_type) %>%
  dplyr::summarize(amp_effect = mean(correct)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  dplyr::rename(false_prime = "0",
                true_prime = "1") %>%
  mutate(int_amp_effect = true_prime - false_prime) %>%
  dplyr::rename(int_false_prime = false_prime, 
                int_true_prime = true_prime)

# Creates an amp_effect column giving the AMP effect on the standard AMP for each subject.
std_joiner <- std_AMP_cleaned %>%
  group_by(subject, prime_type) %>%
  dplyr::summarize(amp_effect = mean(correct)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  dplyr::rename(trump_prime = "0",
                obama_prime = "1") %>%
  mutate(std_amp_effect = obama_prime - trump_prime)

# Creates a full data-frame, with information for each subject on their responses 
# to the post-questions, their standard AMP effect, and their IA-AMP effect.
full_subjects_df <- int_AMP_cleaned %>%
  mutate(influenced = as.numeric(as.character(influenced))) %>%
  group_by(subject) %>%
  dplyr::summarize(influence_rate = mean(influenced)) %>%
  ungroup() %>%
  left_join(int_joiner, by = "subject") %>%
  left_join(screen_qs, by = "subject") %>%
  mutate(influence_rate = as.numeric(influence_rate)) %>%
  left_join(std_joiner, by = "subject") %>%
  filter(politics == "a little democratic" | politics == "somewhat democratic" | politics == "very democratic") # Screen out non-democrats

age_and_gender <- demographics_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  filter(trialcode != "ProlificCode") %>%
  dplyr::select(subject, trialcode, response) %>%
  spread(trialcode, response)

demographs <- full_subjects_df %>%
  left_join(age_and_gender, by = "subject")

```

# Write to disk


```{r write-out}

write_csv(full_subjects_df, "processed/subject_level.csv")
write_csv(int_AMP_cleaned, "processed/intentional_AMP.csv")
write_csv(std_AMP_cleaned, "processed/standard_AMP.csv")
write_csv(demographs, "processed/demographs.csv")
```
