https://stats.stackexchange.com/questions/164471/generating-a-simulated-dataset-from-a-correlation-matrix-with-means-and-standard

```{r}

# columns are group, amp_effect, influence_rate

mu     <- c(0, 0, 0)
stddev <- c(1, 1, 1)

corMat <- matrix(c(1.00, 0.50, 0.60,
                   0.50, 1.00, 0.55,
                   0.60, 0.55, 1.00),
                 ncol = 3)

covMat <- stddev %*% t(stddev) * corMat

set.seed(1)

library(MASS)
library(tidyverse)

dat1 <- mvrnorm(n = 1000, mu = mu, Sigma = covMat, empirical = TRUE) %>%
  as.data.frame() %>%
  rename(group = V1,
         amp_effect = V2,
         influence_rate = V3)

round(colMeans(dat1), 2)
round(cor(dat1), 2)


fit_1 <- lm(group ~ amp_effect,
            data = dat1)



fit_2a <- lm(amp_effect ~ influence_rate,
             data = dat1)

library(broom)
residuals_temp <- augment(fit_1a)

data_with_residuals <- dat1 %>%
  mutate(amp_effect_minus_influence_rate = residuals_temp$.resid)


fit_2b <- lm(group ~ amp_effect_minus_influence_rate,
             data = data_with_residuals)

round(coef(fit_1), 2)
round(coef(fit_2b), 2)

```

# 

```{r}

# columns are group, amp_effect, influence_rate

mu     <- c(0, 0, 0)
stddev <- c(1, 1, 1)

corMat <- matrix(c(1.00, 0.40, 0.40,
                   0.40, 1.00, 0.80,
                   0.40, 0.80, 1.00),
                 ncol = 3)

covMat <- stddev %*% t(stddev) * corMat

set.seed(42)

library(MASS)
library(tidyverse)

dat1 <- mvrnorm(n = 1000, mu = mu, Sigma = covMat, empirical = TRUE) %>%
  as.data.frame() %>%
  rename(group = V1,
         amp_effect = V2,
         influence_rate = V3)

#round(colMeans(dat1), 2)
#round(cor(dat1), 2)


fit_1 <- lm(group ~ amp_effect,
            data = dat1)

fit_2 <- lm(group ~ amp_effect * influence_rate,
            data = dat1)

fit_2a <- lm(group ~ influence_rate,
             data = dat1)

library(broom)
residuals_temp <- augment(fit_1)

data_with_residuals <- dat1 %>%
  mutate(group_minus_influence_rate = residuals_temp$.resid)


fit_2b <- lm(group_minus_influence_rate ~ amp_effect,
             data = data_with_residuals)

round(coef(fit_1), 2)
round(coef(fit_2), 2)
round(coef(fit_2a), 2)
round(coef(fit_2b), 2)

```

