

```{r}

# dependencies
library(tidyverse)
library(effects)

```

# method 1

```{r}

n <- 100000

amp_effect <- runif(n)
influence_rate <- runif(n)

intercept <- 0
amp_effect_beta <- 1
interaction_beta <- -2

# use logistic error -> corresponds to logistic regression. Normal error to probit regression.
Y <- intercept + amp_effect_beta*amp_effect + interaction_beta*amp_effect*influence_rate + rlogis(n)

data_1 <- data.frame(Y = Y, 
                     amp_effect = amp_effect,
                     influence_rate = influence_rate) %>%
  mutate(group = ifelse(Y <= 0.5, 1, 0))

# coef(lm(Y ~ amp_effect * influence_rate, data = data)) # close to the real values

fit_1 <- glm(group ~ amp_effect + amp_effect:influence_rate, 
             family = binomial(link = "logit"),
             data = data_1)

round(coef(fit_1), 2)

# ggplot(data = data_1,
#        aes(x = amp_effect, 
#            y = group)) +
#   geom_smooth(method = "glm",
#               method.args = list(family = "binomial"),
#               fullrange = TRUE) +
#   scale_colour_viridis_c(direction = -1) +
#   theme_classic() +
#   xlim(0, 1) +
#   ylim(0, 1)

predicted_1 <- as.data.frame(effect("amp_effect:influence_rate", fit_1, xlevels = 10))

ggplot(data = predicted_1,
       aes(x = amp_effect, 
           y = fit, 
           colour = influence_rate, 
           group = influence_rate)) +
  geom_line() +
  scale_colour_viridis_c(direction = -1) +
  theme_classic() +
  xlim(0, 1) +
  ylim(0, 1)

```

# method 2

```{r}

# https://sas-and-r.blogspot.com/2009/06/example-72-simulate-data-from-logistic.html

intercept         <- 0
amp_effect        <- rnorm(1000, 1, 1)
amp_effect_beta   <- 1
interaction       <- rnorm(1000, 1, 1)
interaction_beta  <- -2


Y <- intercept + amp_effect*amp_effect_beta + interaction*interaction_beta

prob = exp(Y)/(1 + exp(Y))
r_uniform_data = runif(1000, 0, 1)
group = ifelse(r_uniform_data < prob, 1, 0)

data <- 
  data.frame(group = group,
             prob = prob,
             amp_effect = amp_effect,
             interaction = interaction) %>%
  mutate(interaction_round = as.factor(round(interaction, 0)))

ggplot(data = data,
       aes(x = amp_effect, 
           y = group,
           color = interaction_round, 
           group = interaction_round)) +
  geom_jitter(height = 0.05, width = 0, alpha = 0.2) +
  geom_smooth(method = "glm",
              method.args = list(family = "binomial"),
              fullrange = TRUE,
              se = FALSE) +
  scale_colour_viridis_d(direction = -1) +
  theme_classic()

```

# method 1b gregory corrections

```{r}

n                <- 100000

amp_effect       <- runif(n)
influence_rate   <- runif(n)

intercept        <- 0.5
amp_effect_beta  <- 0
interaction_beta <- 1000

# use logistic error -> corresponds to logistic regression. Normal error to probit regression.
z <- intercept + amp_effect_beta*amp_effect + interaction_beta*amp_effect*influence_rate

pr = 1/(1+exp(-z))         # pass through an inv-logit function

group = rbinom(1000, 1, pr)      # bernoulli response variable

data_1b <- data.frame(influence_rate = influence_rate,
                      amp_effect = amp_effect,
                      group = group)

# coef(lm(Y ~ amp_effect * influence_rate, data = data)) # close to the real values

fit_1 <- glm(group ~ amp_effect + amp_effect:influence_rate, 
             family = binomial(link = "logit"),
             data = data_1b)

round(coef(fit_1), 2)

# ggplot(data = data_1,
#        aes(x = amp_effect, 
#            y = group)) +
#   geom_smooth(method = "glm",
#               method.args = list(family = "binomial"),
#               fullrange = TRUE) +
#   scale_colour_viridis_c(direction = -1) +
#   theme_classic() +
#   xlim(0, 1) +
#   ylim(0, 1)

predicted_1 <- as.data.frame(effect("amp_effect:influence_rate", fit_1, xlevels = 10))

ggplot(data = predicted_1,
       aes(x = amp_effect, 
           y = fit, 
           colour = influence_rate, 
           group = influence_rate)) +
  geom_line() +
  scale_colour_viridis_c(direction = -1) +
  theme_classic()

ggplot(data = predicted_1,
       aes(x = influence_rate, 
           y = fit, 
           colour = amp_effect, 
           group = amp_effect)) +
  geom_line() +
  scale_colour_viridis_c(direction = -1) +
  theme_classic()

```

