---
title: "Simulate data"
author: "Ian Hussey & Jamie Cummins"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE,
                      cache.lazy=TRUE)
```

```{r setup, include=FALSE}

library(tidyverse)
library(patchwork)
library(timesavers)
library(broom)
library(knitr)
library(sjPlot)

knitr::opts_chunk$set(echo = TRUE)

set.seed(1234)

```

# Simulate data 

- 1 Differences in AMP effect moderated by influence rate
- 2 Differences in AMP effect not moderated by influence rate
- 3 No differences in AMP effect, not moderated by influence rate

```{r fig.height=5, fig.width=6}

## 1 Differences in AMP effect moderated by influence rate

# simulate
influence_rate <- seq(from = 0, to = 1, by = 0.001)
b_intercept <- 0
b_influence_rate <- 0.55
sigma <- 0.1

# group 1
error <- rnorm(influence_rate, 0, sigma)
std_amp_effect <- b_intercept + b_influence_rate*influence_rate + error

sim_data_group_1 <- cbind.data.frame(std_amp_effect, influence_rate) %>%
  filter(std_amp_effect <= 1 & std_amp_effect >= -1) %>%
  mutate(group = 1)

# group 0
error <- rnorm(influence_rate, 0, sigma)
std_amp_effect <- b_intercept + b_influence_rate*influence_rate + error

sim_data_group_0 <- cbind.data.frame(std_amp_effect, influence_rate) %>%
  filter(std_amp_effect <= 1 & std_amp_effect >= -1) %>%
  mutate(group = 0,
         std_amp_effect = std_amp_effect*-1)

# combine
sim_data_1 <- rbind(sim_data_group_1, sim_data_group_0)


## 2 Differences in AMP effect not moderated by influence_rate rate

# simulate
influence_rate <- seq(from = 0, to = 1, by = 0.001)
b_intercept <- 0.3
b_influence_rate <- 0
sigma <- 0.1

# group 1
error <- rnorm(influence_rate, 0, sigma)
std_amp_effect <- b_intercept + b_influence_rate*influence_rate + error

sim_data_group_1 <- cbind.data.frame(std_amp_effect, influence_rate) %>%
  filter(std_amp_effect <= 1 & std_amp_effect >= -1) %>%
  mutate(group = 1)

# group 0
error <- rnorm(influence_rate, 0, sigma)
std_amp_effect <- b_intercept + b_influence_rate*influence_rate + error

sim_data_group_0 <- cbind.data.frame(std_amp_effect, influence_rate) %>%
  filter(std_amp_effect <= 1 & std_amp_effect >= -1) %>%
  mutate(group = 0,
         std_amp_effect = std_amp_effect*-1)

# combine
sim_data_2 <- rbind(sim_data_group_1, sim_data_group_0)


## 3 No differences in AMP effect, not moderated by influence_rate rate

# simulate
influence_rate <- seq(from = 0, to = 1, by = 0.001)
b_intercept <- 0
b_influence_rate <- 0
sigma <- 0.1

# group 1
error <- rnorm(influence_rate, 0, sigma)
std_amp_effect <- b_intercept + b_influence_rate*influence_rate + error

sim_data_group_1 <- cbind.data.frame(std_amp_effect, influence_rate) %>%
  filter(std_amp_effect <= 1 & std_amp_effect >= -1) %>%
  mutate(group = 1)

# group 0
error <- rnorm(influence_rate, 0, sigma)
std_amp_effect <- b_intercept + b_influence_rate*influence_rate + error

sim_data_group_0 <- cbind.data.frame(std_amp_effect, influence_rate) %>%
  filter(std_amp_effect <= 1 & std_amp_effect >= -1) %>%
  mutate(group = 0)

# combine
sim_data_3 <- rbind(sim_data_group_1, sim_data_group_0)


# write to disk
write_csv(sim_data_1, "simulation_1_differences_in_AMP_effect_moderated_by_influence_rate.csv")
write_csv(sim_data_2, "simulation_2_differences_in_AMP_effect_not_moderated_by_influence_rate.csv")
write_csv(sim_data_3, "simulation_3_no_differences_in_AMP_effect_not_moderated_by_influence_rate.csv")

```

# Plots

```{r fig.height=3, fig.width=9}

p1 <- 
  ggplot(sim_data_1, 
         aes(influence_rate, std_amp_effect, group = as.factor(group), color = as.factor(group))) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm") +
  scale_colour_viridis_d(end = 0.6) +
  scale_fill_viridis_d(end = 0.6) +
  theme_classic() +
  xlim(0,1) +
  ylim(-1,1) + 
  theme(legend.position = "none") +
  ylab("AMP effect") +
  xlab("Influence rate")

p2 <- 
  ggplot(sim_data_2, 
         aes(influence_rate, std_amp_effect, group = as.factor(group), color = as.factor(group))) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm") +
  scale_colour_viridis_d(end = 0.6) +
  scale_fill_viridis_d(end = 0.6) +
  theme_classic() +
  xlim(0,1) +
  ylim(-1,1) + 
  theme(legend.position = "none") +
  ylab("AMP effect") +
  xlab("Influence rate")

p3 <- 
  ggplot(sim_data_3, 
         aes(influence_rate, std_amp_effect, group = as.factor(group), color = as.factor(group))) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm") +
  scale_colour_viridis_d(end = 0.6) +
  scale_fill_viridis_d(end = 0.6) +
  theme_classic() +
  xlim(0,1) +
  ylim(-1,1) + 
  theme(legend.position = "none") +
  ylab("AMP effect") +
  xlab("Influence rate")

p1 + p2 + p3 + plot_layout(ncol = 3)

```

```{r fig.height=3, fig.width=9}

p1a <- 
  ggplot(sim_data_1, aes(std_amp_effect, group)) +
  geom_smooth(alpha = 0.2,
              method = "glm",
              method.args = list(family = "binomial"),
              fullrange = TRUE)

p2a <- 
  ggplot(sim_data_2, aes(std_amp_effect, group)) +
  geom_smooth(alpha = 0.2,
              method = "glm",
              method.args = list(family = "binomial"),
              fullrange = TRUE)

p3a <- 
  ggplot(sim_data_3, aes(std_amp_effect, group)) +
  geom_smooth(alpha = 0.2,
              method = "glm",
              method.args = list(family = "binomial"),
              fullrange = TRUE)

p1a + p2a + p3a + plot_layout(ncol = 3)

```

# Check with hypothesis tests

```{r}

fit1 <- glm(group ~ std_amp_effect * influence_rate, 
            family = binomial(link = "logit"),
            data = sim_data_1) 

results_1 <- fit1 %>% 
  tidy() %>%
  mutate(lwr = estimate + std.error*1.96,
         upr = estimate - std.error*1.96) %>%
  select(term, estimate, lwr, upr, p.value) %>%
  rename(log_odds = estimate) %>%
  filter(term != "(Intercept)") %>%
  round_df(2) %>%
  mutate(simultion = 1)

#plot_model(fit1, transform = NULL)


## 2 Differences in AMP effect not moderated by influence rate

fit2 <- glm(group ~ std_amp_effect + influence_rate, 
            family = binomial(link = "logit"),
            data = sim_data_2) 

results_2 <- fit2 %>% 
  tidy() %>%
  mutate(lwr = estimate + std.error*1.96,
         upr = estimate - std.error*1.96) %>%
  select(term, estimate, lwr, upr, p.value) %>%
  rename(log_odds = estimate) %>%
  filter(term != "(Intercept)") %>%
  round_df(2) %>%
  mutate(simultion = 2)

#plot_model(fit2, transform = NULL)


## 3 No differences in AMP effect, not moderated by influence rate


fit3 <- glm(group ~ std_amp_effect + influence_rate, 
            family = binomial(link = "logit"),
            data = sim_data_3) 

results_3 <- fit3 %>% 
  tidy() %>%
  mutate(lwr = estimate + std.error*1.96,
         upr = estimate - std.error*1.96) %>%
  select(term, estimate, lwr, upr, p.value) %>%
  rename(log_odds = estimate) %>%
  filter(term != "(Intercept)") %>%
  round_df(2) %>%
  mutate(simultion = 3)

#plot_model(fit3, transform = NULL)

rbind(results_1, results_2, results_3)

```
