---
title: "Study 4"
subtitle: "Processing"
author: "Ian Hussey & Jamie Cummins"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r include=FALSE}

knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE)

```

```{r}

# dependencies
library(tidyverse)

# get data
demographics_df    <- read.csv("raw/demographics.csv")
IA_AMP_df          <- read.csv("raw/modified_intentionality_amp.csv")
questions_df       <- read.csv("raw/post_questions.csv")

```

# Demographics and self reports

```{r}

# match Prolific IDs to subject numbers (for payment processing)
prolificid_df <- demographics_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  filter(trialcode == "ProlificCode") %>%
  dplyr::select(subject, response) 

demographics_data <- demographics_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  filter(trialcode != "ProlificCode") %>%
  select(subject, trialcode, response) %>%
  spread(trialcode, response) %>%
  mutate(subject = as.character(subject))

self_report_data <- questions_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  select(subject, trialcode, response) %>%
  group_by(subject) %>%
  spread(trialcode, response) %>%
  ungroup %>% 
  mutate(subject = as.character(subject)) %>%
  mutate(party = ifelse(politics %in% c("a little republican", "somewhat republican", "very republican"), "republican",
                        ifelse(politics %in% c("a little democratic", "somewhat democratic", "very democratic"), "democrat",
                               "neither/moderate")))

```

# IA AMP effects and influence rates

```{r}

IA_AMP_cleaned <- IA_AMP_df %>%
  
  # reshape influence variable
  mutate(influenced = as.numeric(as.character(lead(correct)))) %>%
  
  # keep only test blocks and ratings trials
  filter(!str_detect(trialcode, "intention_check"),
         blockcode == "test") %>%
  
  # mutate some vars
  mutate(domain = ifelse(trialcode %in% c("prime_positive", "prime_negative"), "IA_AMP_positive_negative",
                         ifelse(trialcode %in% c("prime_obama", "prime_trump"), "IA_AMP_obama_trump", NA)),
         prime_type = ifelse(trialcode %in% c("prime_obama", "prime_positive"), "prime_type_A", "prime_type_B"),
         subject = as.character(subject),
         rating = as.numeric(as.character(correct))) %>%
  
  # exclude participants without the right number of AMP trials
  group_by(subject) %>% 
  filter(n() == 240) %>%
  ungroup() %>%
  select(subject, domain, prime_type, rating, influenced) %>%
  
  # exclude those who didn't have the right number of trials on the screener
  mutate(subject = as.character(subject))

# score amp effect
## overall AMP effects  
IA_AMP_effects <- IA_AMP_cleaned %>%
  group_by(subject, domain, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(amp_effect = round(prime_type_A - prime_type_B, 2)) %>%
  select(subject, domain, amp_effect) %>%
  spread(domain, amp_effect) %>%
  rename(IA_AMP_effect_obama_trump = IA_AMP_obama_trump,
         IA_AMP_effect_positive_negative = IA_AMP_positive_negative)

## AMP effects by influenced/noninfluenced trials
IA_AMP_effects_by_influence <- IA_AMP_cleaned %>%
  mutate(influenced = dplyr::recode(influenced,
                                    "0" = "not_influenced",
                                    "1" = "influenced")) %>%
  group_by(subject, domain, prime_type, influenced) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(amp_effect = round(prime_type_A - prime_type_B, 2),
         amp_type = paste(domain, influenced, sep = "_")) %>%
  select(subject, amp_type, amp_effect) %>%
  spread(amp_type, amp_effect)  %>%
  rename(IA_AMP_effect_obama_trump_influenced = IA_AMP_obama_trump_influenced,
         IA_AMP_effect_obama_trump_not_influenced = IA_AMP_obama_trump_not_influenced,
         IA_AMP_effect_positive_negative_influenced = IA_AMP_positive_negative_influenced,
         IA_AMP_effect_positive_negative_not_influenced = IA_AMP_positive_negative_not_influenced)

# score influence rates
IA_AMP_influence_rate <- IA_AMP_cleaned %>%
  group_by(subject, domain) %>%
  summarize(influence_rate = round(mean(influenced), 2)) %>%
  ungroup() %>%
  spread(domain, influence_rate) %>%
  rename(influence_rate_obama_trump = IA_AMP_obama_trump,
         influence_rate_positive_negative = IA_AMP_positive_negative)

IA_AMP_data <- IA_AMP_effects %>%
  full_join(IA_AMP_effects_by_influence, by = "subject") %>%
  full_join(IA_AMP_influence_rate, by = "subject")

```

# Screen for complete data

```{r}

complete_demographics_data <- demographics_data %>%
  na.omit() %>%
  distinct(subject)

complete_self_report_data <- self_report_data %>%
  na.omit() %>%
  distinct(subject)

complete_IA_AMP_data <- IA_AMP_data %>%
  na.omit() %>%
  distinct(subject)

complete_data <- complete_demographics_data %>%
  semi_join(complete_self_report_data, by = "subject") %>%
  semi_join(complete_IA_AMP_data, by = "subject") %>%
  mutate(complete_data = TRUE)

```

# Write to disk

```{r}

# combine
processed_data <- demographics_data %>%
  full_join(IA_AMP_data, by = "subject") %>%
  full_join(self_report_data, by = "subject") %>%
  full_join(complete_data, by = "subject") %>%
  mutate(complete_data = ifelse(is.na(complete_data), FALSE, complete_data))

# long format AMP data
trial_level_ia_amp_data <- processed_data %>%
  right_join(IA_AMP_cleaned, by = "subject") %>%
  filter(domain == "IA_AMP_positive_negative") %>%
  select(subject, prime_type, rating, influenced, self_exclusion_1, complete_data)

# write to disk
write_csv(processed_data, "processed/processed_data.csv")
write_csv(trial_level_ia_amp_data, "processed/trial_level_ia_amp_positive_negative_data.csv")

```
