
# Same domain

```{r fig.height=5, fig.width=5}

# fit combined model
fit_temp <- lm(IA_AMP_effect_obama_trump ~ party * influence_rate_obama_trump,
               data = task_level_data_exclusions)

# predictions
predicted <- 
  as.data.frame(effect("party:influence_rate_obama_trump", fit_temp, xlevels = 101)) %>%
  round_df(2) 

# plot
p1 <- ggplot(data = predicted,
             aes(x = party, 
                 y = fit, 
                 colour = influence_rate_obama_trump, 
                 group = influence_rate_obama_trump)) +
  geom_line() +
  scale_colour_viridis_c(direction = -1) +
  theme_classic() + 
  ylab("Politics IA-AMP's effect") +
  xlab("Party") +
  labs(colour = "Politics IA-AMP's\ninfluence-awareness rate") +
  # scale_y_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1.00), 
  #                    labels = c("0.00\n(Negative) ", "0.25", "0.50", "0.75", "1.00\n(Positive) "), 
  #                    limits = c(0, 1)) + 
  theme(legend.position = c(0.77, 0.30))

tab_model(fit_temp, 
          digits.p = 20)

p1

```

# Different domain

```{r fig.height=5, fig.width=5}

# fit combined model
fit_temp <- lm(IA_AMP_effect_obama_trump ~ party * influence_rate_positive_negative,
               data = task_level_data_exclusions)

# predictions
predicted <- 
  as.data.frame(effect("party:influence_rate_positive_negative", fit_temp, xlevels = 101)) %>%
  round_df(2) 

# plot
p2 <- ggplot(data = predicted,
             aes(x = party, 
                 y = fit, 
                 colour = influence_rate_positive_negative, 
                 group = influence_rate_positive_negative)) +
  geom_line() +
  scale_colour_viridis_c(direction = -1) +
  theme_classic() + 
  ylab("Politics IA-AMP's effect") +
  xlab("Party") +
  labs(colour = "Positive-negative IA-AMP's\ninfluence-awareness rate") +
  # scale_y_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1.00), 
  #                    labels = c("0.00\n(Negative) ", "0.25", "0.50", "0.75", "1.00\n(Positive) "), 
  #                    limits = c(0, 1)) + 
  theme(legend.position = c(0.77, 0.30))

tab_model(fit_temp, 
          digits.p = 20)

p2

```