---
title: "Predictive ability of the AMP"
subtitle: "Simulation 1: Differences in AMP effect moderated by influence rate"
author: "Ian Hussey & Jamie Cummins"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    number_sections: no
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      cache.lazy = FALSE)
```

```{r}

# dependencies
library(tidyverse)
library(psych)
library(knitr)
library(sjPlot)
library(broom)
library(kableExtra)
library(timesavers)
library(patchwork)

# plot function
source("geom_flat_violin.R")

# disable scientific notation
options(scipen = 999) 

# comment out if knitting to pdf
options(knitr.table.format = "html")

# get data
input_data <- read.csv("../simulated_data/simulation_1_differences_in_AMP_effect_moderated_by_influence_rate.csv")
#input_data <- read.csv("../simulated_data/simulation_2_differences_in_AMP_effect_not_moderated_by_influence_rate.csv")
#input_data <- read.csv("../simulated_data/simulation_3_no_differences_in_AMP_effect_not_moderated_by_influence_rate.csv")

```

# plot raw data

```{r}

# distribution of simulated data
ggplot(input_data, aes(influence_rate, std_amp_effect, color = as.factor(group))) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm") +
  scale_colour_viridis_d(end = .6) +
  theme_classic() +
  xlim(0,1) +
  ylim(-1,1)

# impact of influence on amp effects
ggplot(input_data, aes(x = as.factor(group), y = std_amp_effect, color = influence_rate)) + 
  geom_jitter(alpha = 0.4, width = .05, height = 0.05) + 
  theme_classic() +
  scale_colour_viridis_c() +
  ylim(-1,1)

```

# Model 1 - AMP effect predicts group membership

Binomial logistic regression: group ~ predictor

```{r}

# model
model_1 <-   
  glm(group ~ std_amp_effect, 
      family = binomial(link = "logit"),
      data = input_data)

sjt.glm(model_1, exp.coef = FALSE)

# Assess model fit

## extraction predicted probabilities
prob <- predict(model_1, type = c("response"), se.fit = TRUE)

## add these probabilities back to the original data frame (omitting missing values) 
predictions <- input_data %>%
  select(group) %>%
  na.omit %>%
  mutate(prob = prob$fit)

# plot
ggplot(data = predictions, 
         aes(x = as.factor(group), 
             y = prob, 
             fill = as.factor(group))) +
  geom_flat_violin(position = position_nudge(x = .2, y = 0), 
                   alpha = .8) +
  geom_point(aes(y = prob, 
                 color = as.factor(group)), 
             position = position_jitter(width = .15), 
             size = .5, 
             alpha = 0.5) +
  guides(fill = FALSE) +
  guides(color = FALSE) +
  scale_colour_viridis_d(end = 0.6) +
  scale_fill_viridis_d(end = 0.6) +
  coord_flip() +
  theme_classic() +
  xlab("Group") +
  ylab("Predicted probability") +
  ggtitle("AMP")

```


```{r}

# model
model_2 <-   
  glm(group ~ std_amp_effect, 
      family = binomial(link = "logit"),
      weights = influence_rate,
      data = input_data)

sjt.glm(model_2, exp.coef = FALSE)

# Assess model fit

## extraction predicted probabilities
prob_2 <- predict(model_2, type = c("response"), se.fit = TRUE)

## add these probabilities back to the original data frame (omitting missing values) 
predictions_2 <- input_data %>%
  select(group) %>%
  na.omit %>%
  mutate(prob = prob_2$fit)

# plot
ggplot(data = predictions_2, 
         aes(x = as.factor(group), 
             y = prob, 
             fill = as.factor(group))) +
  geom_flat_violin(position = position_nudge(x = .2, y = 0), 
                   alpha = .8) +
  geom_point(aes(y = prob, 
                 color = as.factor(group)), 
             position = position_jitter(width = .15), 
             size = .5, 
             alpha = 0.5) +
  guides(fill = FALSE) +
  guides(color = FALSE) +
  scale_colour_viridis_d(end = 0.6) +
  scale_fill_viridis_d(end = 0.6) +
  coord_flip() +
  theme_classic() +
  xlab("Group") +
  ylab("Predicted probability") +
  ggtitle("AMP")

```


```{r}

effsize::cohen.d(prob ~ group, data = predictions)

effsize::cohen.d(prob ~ group, data = predictions_2)

```
