---
title: "Study 4"
subtitle: "Processing"
author: "Ian Hussey & Jamie Cummins"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r include=FALSE}

knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE)

```

```{r}

# dependencies
library(tidyverse)

# get data
demographics_df    <- read.csv("raw/demographics.csv")
posneg_IA_AMP_df   <- read.csv("raw/modified_intentionality_amp.csv")
politics_IA_AMP_df <- read.csv("raw/modified_intentionality_amp.csv")
questions_df       <- read.csv("raw/post_questions.csv")

```

# Demographics and self reports

```{r}

# match Prolific IDs to subject numbers (for payment processing)
prolificid_df <- demographics_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  filter(trialcode == "ProlificCode") %>%
  dplyr::select(subject, response) 

demographics_data <- demographics_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  filter(trialcode != "ProlificCode") %>%
  select(subject, trialcode, response) %>%
  spread(trialcode, response) %>%
  mutate(subject = as.character(subject))


allowed_response_options <- c("none", "a few", "less than half", "about half", "more than half", "most", "all")

self_report_data <- questions_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  select(subject, trialcode, response) %>%
  group_by(subject) %>%
  spread(trialcode, response) %>%
  ungroup %>% 
  mutate(subject = as.character(subject)) %>%
  # some pilot data that used alternative reponse options made it into the data. exclude this.
  mutate(awareness = ifelse(!(influence_general_pn %in% allowed_response_options), NA, as.character(awareness)),
         influence_general_pn = ifelse(!(influence_general_pn %in% allowed_response_options), NA, as.character(influence_general_pn)),
         intentionality_pn    = ifelse(!(intentionality_pn %in% allowed_response_options), NA, as.character(intentionality_pn)),
         intentionality_to    = ifelse(!(intentionality_to %in% allowed_response_options), NA, as.character(intentionality_to)),
         unintentionality_pn  = ifelse(!(unintentionality_pn %in% allowed_response_options), NA, as.character(unintentionality_pn)),
         unintentionality_to  = ifelse(!(unintentionality_to %in% allowed_response_options), NA, as.character(unintentionality_to)),
         # recode likert from string to integer
         awareness = dplyr::recode(as.character(awareness),
                                   `none`           = 1,
                                   `a few`          = 2,
                                   `less than half` = 3,
                                   `about half`     = 4,
                                   `more than half` = 5,
                                   `most`           = 6,
                                   `all`            = 7),
         influence_general_pn = dplyr::recode(as.character(influence_general_pn),
                                              `none`           = 1,
                                              `a few`          = 2,
                                              `less than half` = 3,
                                              `about half`     = 4,
                                              `more than half` = 5,
                                              `most`           = 6,
                                              `all`            = 7),
         influence_general_to = dplyr::recode(as.character(influence_general_to),
                                              `none`           = 1,
                                              `a few`          = 2,
                                              `less than half` = 3,
                                              `about half`     = 4,
                                              `more than half` = 5,
                                              `most`           = 6,
                                              `all`            = 7),
         intentionality_pn = dplyr::recode(as.character(intentionality_pn),
                                           `none`           = 1,
                                           `a few`          = 2,
                                           `less than half` = 3,
                                           `about half`     = 4,
                                           `more than half` = 5,
                                           `most`           = 6,
                                           `all`            = 7),
         intentionality_to = dplyr::recode(as.character(intentionality_to),
                                           `none`           = 1,
                                           `a few`          = 2,
                                           `less than half` = 3,
                                           `about half`     = 4,
                                           `more than half` = 5,
                                           `most`           = 6,
                                           `all`            = 7),
         unintentionality_pn = dplyr::recode(as.character(unintentionality_pn),
                                             `none`           = 1,
                                             `a few`          = 2,
                                             `less than half` = 3,
                                             `about half`     = 4,
                                             `more than half` = 5,
                                             `most`           = 6,
                                             `all`            = 7),
         unintentionality_to = dplyr::recode(as.character(unintentionality_to),
                                             `none`           = 1,
                                             `a few`          = 2,
                                             `less than half` = 3,
                                             `about half`     = 4,
                                             `more than half` = 5,
                                             `most`           = 6,
                                             `all`            = 7),
         party = ifelse(politics %in% c("a little republican", 
                                        "somewhat republican", 
                                        "very republican"), "republican",
                        ifelse(politics %in% c("a little democratic", 
                                               "somewhat democratic", 
                                               "very democratic"), "democrat", "neither/moderate")))

```

# Politics IA AMP effects and influence rates

```{r}

politics_IA_AMP_cleaned <- politics_IA_AMP_df %>%
  
  mutate(influenced = as.numeric(as.character(lead(correct)))) %>%
  filter(trialcode == "prime_obama" | trialcode == "prime_trump") %>%
  
  rename(prime_type = trialcode) %>%
  mutate(rating = as.numeric(as.character(correct))) %>%
  
  # keep only test blocks and ratings trials
  filter(!str_detect(prime_type, "intention_check"),
         blockcode == "test") %>%
  
  # mutate some vars
  mutate(prime_type = ifelse(prime_type %in% c("prime_obama", "prime_positive"), "prime_type_A", "prime_type_B"),
         subject = as.character(subject),
         rating = as.numeric(as.character(correct))) %>%
  
  # exclude participants without the right number of AMP trials
  group_by(subject) %>% 
  filter(n() == 72) %>%
  ungroup() %>%
  select(subject, prime_type, rating, influenced) %>%
  
  # exclude those who didn't have the right number of trials on the screener
  mutate(subject = as.character(subject))

# score amp effect
politics_IA_AMP_effect <- politics_IA_AMP_cleaned %>%
  group_by(subject, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_effect_obama_trump = round(prime_type_A - prime_type_B, 2)) %>%
  select(subject, IA_AMP_effect_obama_trump) 

# score amp effect for influenced trials
politics_IA_AMP_effect_influenced <- politics_IA_AMP_cleaned %>%
  filter(influenced == TRUE) %>%
  group_by(subject, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_effect_obama_trump_influenced = round(prime_type_A - prime_type_B, 2)) %>%
  select(subject, IA_AMP_effect_obama_trump_influenced) 

# score amp effect for uninfluenced trials
politics_IA_AMP_effect_uninfluenced <- politics_IA_AMP_cleaned %>%
  filter(influenced == FALSE) %>%
  group_by(subject, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_effect_obama_trump_uninfluenced = round(prime_type_A - prime_type_B, 2)) %>%
  select(subject, IA_AMP_effect_obama_trump_uninfluenced) 

# score influence rates
politics_IA_AMP_influence_rate <- politics_IA_AMP_cleaned %>%
  group_by(subject) %>%
  summarize(influence_rate_obama_trump = round(mean(influenced), 2)) %>%
  ungroup()

politics_IA_AMP_data <- politics_IA_AMP_effect %>%
  full_join(politics_IA_AMP_effect_influenced, by = "subject") %>%
  full_join(politics_IA_AMP_effect_uninfluenced, by = "subject") %>%
  full_join(politics_IA_AMP_influence_rate, by = "subject")

```

# Pos-neg IA AMP effects and influence rates

```{r}

posneg_IA_AMP_cleaned <- posneg_IA_AMP_df %>%

  mutate(influenced = as.numeric(as.character(lead(correct)))) %>%
  filter(trialcode == "prime_positive" | trialcode == "prime_negative") %>% 
  
  rename(prime_type = trialcode) %>%
  mutate(rating = as.numeric(as.character(correct))) %>%
  
  # keep only test blocks and ratings trials
  filter(!str_detect(prime_type, "intention_check"),
         blockcode == "test") %>%
  
  # mutate some vars
  mutate(prime_type = ifelse(prime_type %in% c("prime_obama", "prime_positive"), "prime_type_A", "prime_type_B"),
         subject = as.character(subject),
         rating = as.numeric(as.character(correct))) %>%
  
  # exclude participants without the right number of AMP trials
  group_by(subject) %>% 
  filter(n() == 72) %>%
  ungroup() %>%
  select(subject, prime_type, rating, influenced) %>%
  
  # exclude those who didn't have the right number of trials on the screener
  mutate(subject = as.character(subject))

# score amp effect
posneg_IA_AMP_effect <- posneg_IA_AMP_cleaned %>%
  group_by(subject, prime_type) %>%
  summarize(amp_effect = mean(rating)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  mutate(IA_AMP_effect_positive_negative = round(prime_type_A - prime_type_B, 2)) %>%
  select(subject, IA_AMP_effect_positive_negative) 

# score influence rates
posneg_IA_AMP_influence_rate <- posneg_IA_AMP_cleaned %>%
  group_by(subject) %>%
  summarize(influence_rate_positive_negative = round(mean(influenced), 2)) %>%
  ungroup()

posneg_IA_AMP_data <- full_join(posneg_IA_AMP_effect, 
                                posneg_IA_AMP_influence_rate, 
                                by = "subject")

```

# Screen for complete data

```{r}

complete_demographics_data <- demographics_data %>%
  na.omit() %>%
  distinct(subject)

complete_self_report_data <- self_report_data %>%
  na.omit() %>%
  distinct(subject)

complete_politics_IA_AMP_data <- politics_IA_AMP_data %>%
  na.omit() %>%
  distinct(subject)

complete_posneg_IA_AMP_data <- posneg_IA_AMP_data %>%
  na.omit() %>%
  distinct(subject)

complete_data <- complete_demographics_data %>%
  semi_join(complete_self_report_data, by = "subject") %>%
  semi_join(complete_politics_IA_AMP_data, by = "subject") %>%
  semi_join(complete_posneg_IA_AMP_data, by = "subject") %>%
  mutate(complete_data = TRUE)

```

# Write to disk

```{r}

# combine
processed_data <- demographics_data %>%
  full_join(politics_IA_AMP_data, by = "subject") %>%
  full_join(posneg_IA_AMP_data, by = "subject") %>%
  full_join(self_report_data, by = "subject") %>%
  full_join(complete_data, by = "subject") %>%
  mutate(complete_data = ifelse(is.na(complete_data), FALSE, complete_data))

# long format politics IA AMP data
trial_level_politics_ia_amp_data <- processed_data %>%
  right_join(politics_IA_AMP_cleaned, by = "subject") %>%
  dplyr::select(subject, age, gender, party, 
                prime_type, rating, influenced, self_exclusion_1, complete_data)

# long format posneg IA AMP data
trial_level_posneg_ia_amp_data <- processed_data %>%
  right_join(posneg_IA_AMP_cleaned, by = "subject") %>%
  dplyr::select(subject, age, gender, party, 
                prime_type, rating, influenced, self_exclusion_1, complete_data)

# write to disk
write_csv(processed_data, "processed/processed_data.csv")
write_csv(trial_level_politics_ia_amp_data, "processed/trial_level_ia_amp_obama_trump_data.csv")
write_csv(trial_level_posneg_ia_amp_data, "processed/trial_level_ia_amp_positive_negative_data.csv")

```




