---
title: "Study 4"
subtitle: "Processing"
author: "Jamie Cummins & Ian Hussey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r}
library(tidyverse)

dems_std_df        <- read.csv("raw/study4_std.csv")
reps_std_df        <- read.csv("raw/standard_amp_18_08_12.csv")
dems_int_df        <- read.csv("raw/study4_int.csv")
reps_int_df        <- read.csv("raw/modified_intentionality_amp_18_08_12.csv")
demos_dems_df      <- read.csv("raw/study4_demographs.csv")
demos_reps_df      <- read.csv("raw/demographics_18_08_12.csv")
questions_dems_df  <- read.csv("raw/study4_qs.csv")
questions_reps_df  <- read.csv("raw/post-questions_18_08_12.csv")

```

```{r questions and demographics}

# Join dfs
demographics_df <- rbind.data.frame(demos_dems_df, demos_reps_df)
questions_df <- rbind.data.frame(questions_dems_df, questions_reps_df)


# match Prolific IDs to subject numbers (for payment processing)
prolificid_df <- demographics_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  filter(trialcode == "ProlificCode") %>%
  dplyr::select(subject, response) 

# Screen questions df for unique values, thus removing duplicates
self_exclusion <- questions_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  dplyr::select(subject, trialcode, response)

# Join the above two dfs, filter for only the appropriate number of rows
screen <- full_join(prolificid_df, self_exclusion, by="subject") %>%
  group_by(subject) %>% 
  filter(n() == 8) %>%
  dplyr::rename(prolificid = response.x, 
                response = response.y) %>%
  mutate(response = as.character(response)) %>%
  ungroup()

# Take the questions_df, remove potential duplicates, and then spread
screen_qs <- questions_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  select(subject, trialcode, response) %>%
  group_by(subject) %>%
  spread(trialcode, response) %>%
  ungroup() %>% 
  na.omit

```



``` {r}
d_std_df <- dems_std_df %>%
  mutate(party = 1)

r_std_df <- reps_std_df %>%
  mutate(party = -1)

full_std_df <- rbind.data.frame(d_std_df, r_std_df)
```

```{r}
d_int_df <- dems_int_df %>%
  mutate(party = 1)

r_int_df <- reps_int_df %>%
  mutate(party = -1)

full_int_df <- rbind.data.frame(d_int_df, r_int_df)
```

```{r}
cleaned_int_df <- full_int_df %>%
  mutate(influenced = ifelse(trialcode == "intention_check" & correct == 1, 1, 0)) %>%
  mutate(influenced = lead(influenced)) %>%
  filter(trialcode == "prime_positive" | trialcode == "prime_negative") %>%
  mutate(trialcode = ifelse(trialcode == "prime_positive", 1, 0)) %>%  
  group_by(subject) %>% 
  filter(n() == 72) %>%
  semi_join(., screen, by = "subject") %>%
  dplyr::rename(prime_type = trialcode) %>%
  ungroup()

cleaned_std_df <- full_std_df %>%
  filter(trialcode == "prime_obama" | trialcode == "prime_trump") %>%
  mutate(trialcode = ifelse(trialcode == "prime_obama", 1, 0)) %>%
  group_by(subject) %>% 
  filter(n() == 72) %>%
  semi_join(., screen, by = "subject") %>%
  semi_join(., cleaned_int_df, by = "subject") %>% # Check for parity
  dplyr::rename(prime_type = trialcode) %>%
  ungroup()

democrat_subs <- cleaned_std_df %>%
  filter(party == 1) %>%
  select(subject) %>%
  unique() %>%
  mutate(subject = as.character(subject))
democrat_subs <- as.list(democrat_subs)


```

```{r}
subject_int_df <- cleaned_int_df %>%
  group_by(subject, prime_type) %>%
  dplyr::summarize(amp_effect = mean(correct)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  dplyr::rename(false_prime = "0",
                true_prime = "1") %>%
  mutate(int_amp_effect = true_prime - false_prime) %>%
  dplyr::rename(int_false_prime = false_prime, 
                int_true_prime = true_prime)

subject_std_df <- cleaned_std_df %>%
  group_by(subject, prime_type) %>%
  dplyr::summarize(amp_effect = mean(correct)) %>%
  ungroup() %>%
  spread(prime_type, amp_effect) %>%
  dplyr::rename(trump_prime = "0",
                obama_prime = "1") %>%
  mutate(std_amp_effect = obama_prime - trump_prime)


# Create the main full subjects data frame
full_subjects_df <- cleaned_int_df %>%
  mutate(influenced = as.numeric(as.character(influenced))) %>% # Need to calculate influence rate here as opposed to above for int_joiner because it screws up the data frame if computed above!
  group_by(subject) %>%
  dplyr::summarize(influence_rate = mean(influenced)) %>%
  ungroup() %>%
  left_join(subject_int_df, by = "subject") %>%
  left_join(screen_qs, by = "subject") %>%
  left_join(subject_std_df, by = "subject") %>%
  filter(politics != "neither/moderate") %>% # Screen out politically-neutral respondents 
# still need to filter out participants who self-reported politics =/= their group
  mutate(abs_amp_effect = abs(std_amp_effect)) %>%
  mutate(party = ifelse(politics == "very democratic" | politics == "somewhat democratic" | politics == "a little democratic", 1, -1))

age_and_gender <- demographics_df %>%
  distinct(subject, trialcode, .keep_all = TRUE) %>%
  filter(trialcode != "ProlificCode") %>%
  dplyr::select(subject, trialcode, response) %>%
  spread(trialcode, response)

demographs_df <- full_subjects_df %>%
  left_join(age_and_gender, by = "subject")

plotting_df <- full_subjects_df %>%
  group_by(party) %>%
  dplyr::summarize(mean_std = mean(std_amp_effect), 
                   sd_std = sd(std_amp_effect),
                   mean_int = mean(int_amp_effect), 
                   sd_int = sd(int_amp_effect))


```


# Write to disk


```{r write-out}

write_csv(full_subjects_df, "processed/subject_level.csv")
write_csv(cleaned_int_df, "processed/intentional_AMP.csv")
write_csv(cleaned_int_df, "processed/standard_AMP.csv")
write_csv(demographs_df, "processed/demographs.csv")
write_csv(plotting_df, "processed/plotting.csv")
```
















